import type { Metadata } from "next";
import { Ubuntu_Sans_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar/NavigationBar";

const ubuntu_Sans_Mono = Ubuntu_Sans_Mono({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${ubuntu_Sans_Mono.className} antialiased`}>
        {children}
        <NavBar />
      </body>
    </html>
  );
}
